on:
  push:
    tags:
    - '*'
name: Publish to market
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn test
      - uses: actions/checkout@v2
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:          
          CI: true
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

